CREATE TABLE users(
user_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150),
email VARCHAR(150) NOT NULL,
password VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products(
product_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150),
description TEXT,
price DECIMAL(10,2),
image_path VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE form(
id INT AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(150),
lastname VARCHAR(150),
email VARCHAR(150) NOT NULL,
country VARCHAR(100),
message TEXT,
details VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
